name: mybinder-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - networkx
  - matplotlib
  - python-louvain
  - graphviz
  - pygraphviz
  - scikit-learn
  - pandas
  - nltk
  - gensim
  - tweepy
  - pip
  - pip:
    - vaderSentiment
